# Data Preparation: Loading, Cleaning, and Feature Engineering

This notebook handles:
1. Loading raw data files (Affordability Gap and College Results)
2. Data cleaning and merging
3. Feature engineering (treatment, outcomes, confounders)
4. Saving analysis-ready dataset

**Expected Runtime:** 10-15 minutes

**Outputs:**
- `/outputs/data/merged_clean.csv`
- `/outputs/data/analysis_ready.csv`

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Configure display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully!")

Libraries imported successfully!

# Data Loading

**Testing Directions:** 
- Verify both datasets load without errors
- Check shapes (~21K rows for Affordability, ~6K rows for College Results)
- Inspect first few rows for data quality
- Confirm no parsing errors or corrupted data

In [2]:
# Load Affordability Gap Data
affordability_file = '../Affordability Gap Data AY2022-23 2.17.25.xlsx - Affordability_latest_02-17-25 1.csv'

print("Loading Affordability Gap Data...")
df_affordability = pd.read_csv(affordability_file, low_memory=False)

print(f"✓ Affordability data loaded successfully!")
print(f"  Shape: {df_affordability.shape}")
print(f"  Columns: {df_affordability.shape[1]}")
print(f"\nFirst 5 rows:")
df_affordability.head()

Loading Affordability Gap Data...
✓ Affordability data loaded successfully!
  Shape: (21299, 79)
  Columns: 79

First 5 rows:

,Unit ID,Institution Name,City,State Abbreviation,Sector Name,Sector,MSI Status,MSI Type,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,Average Work Study Award,"Cost of Attendance: In State, On Campus",Cost of Attendance: Out of State,Cost of Attendance: In District,Cost of Attendance: In State,Annual Income Estimate,Student Family Earnings Ceiling,State Minimum Wage,Income Earned from Working 10 Hours a Week at State's Minimum Wage,Net Price,Affordability Gap (net price minus income earned working 10 hrs at min wage),Weekly Hours to Close Gap,100% TTD Affordability Gap,150% TTD Affordability Gap,CPI Index,Monthly Center-Based Child Care Cost,Annual Center-Based Child Care Cost,Adjusted Monthly Center-Based Child Care Cost,Monthly Home-Based Child Care Cost,Adjusted Monthly Home-Based Child Care Cost,Annual Home-Based Child Care Cost,Student Parent Affordability Gap: Center-Based Care,Student Parent Affordability Gap: Home-Based Care,Weekly Hours to Close Gap: Center-Based Care,Weekly Hours to Close Gap: Home-Based Care,100% TTD Student Parent Affordability Gap: Center-Based Care,100% TTD Student Parent Affordability Gap: Home-Based Care,150% TTD Student Parent Affordability Gap: Center-Based Care,150% TTD Student Parent Affordability Gap: Home-Based Care,Adjusted Annual Home-Based Child Care Cost,Adjusted Annual Center-Based Child Care Cost,Highest Degree Offered Name,Highest Degree Offered,Highest Level Offered Name,Highest Level Offered,Combined Statistical Area,Degree of Localization Name,Degree of Localization,Institution Level Name,Institution Level,Institution Size Category Name,Institution Size Category,County Name,Zip Code,State,State Code (FIPS),Latitude,Longitude,Region,Region #,Sub Region,Sub Region #,Admissions Website,Institution Status,2000 Carnegie Classification Name,2000 Carnegie Classification,2015 Carnegie Classification Name,2015 Carnegie Classification,2018 Carnegie Classification Name,2018 Carnegie Classification,2021 Carnegie Classification Name,2021 Carnegie Classification,County Code,Control of Institution
0,371928,Modern Technology School,Fountain Valley,CA,"Private for-profit, 2-year",6,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3040.0,NaN,NaN,NaN,NaN,7000.0,30000.0,14.00,140.0,22711.0,15711.0,22.4,31422.0,47133.0,1.08,1665.2,19982.4,1795.42,1522.8,1641.88,18273.6,37256.02,35413.60,53.22,50.59,74512.04,70827.20,149024.08,141654.40,19702.56,21545.04,Non-degree granting,0,"At least 2, but less than 4 academic yrs",4,348,City: Small,13,At least 2 but less than 4 years,2,"Under 1,000",1,Orange County,92708-9821,California,6,33.72,-117.92,West,4.0,Pacific Division,9.0,https://www.mtschool.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,6059,3
1,369668,Central Pennsylvania Institute of Science and ...,Pleasant Gap,PA,"Public, 2-year",4,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1597.0,NaN,NaN,NaN,NaN,3625.0,30000.0,7.25,72.5,9184.0,5559.0,15.3,11118.0,16677.0,1.08,1392.8,16713.6,1501.72,1233.6,1330.07,14803.2,23579.60,21519.81,65.05,59.36,47159.20,43039.62,94318.40,86079.24,15960.84,18020.64,Associate's degree,40,Associate's degree,3,524,Rural: Fringe,41,At least 2 but less than 4 years,2,"Under 1,000",1,Centre County,16823,Pennsylvania,42,40.88,-77.74,Northeast,1.0,Middle Atlantic Division,2.0,,A,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,"Not applicable, not in Carnegie universe (not ...",-2,Special Focus Two-Year: Technical Professions,11,42027,1
2,369516,Bryan University,Springfield,MO,"Private for-profit, 4-year or above",3,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2165.0,.,15693.0,15693.0,15693.0,5150.0,30000.0,10.30,103.0,21316.0,16166.0,31.4,64664.0,96996.0,1.08,1110.0,13320.0,1196.80,1258.8,1357.24,15105.6,30527.62,32452.86,59.28,63.02,122110.48,129811.44,183165.72,194717.16,16286.88,14361.60,Master's degree,20,Master's degree,7,-2,City: Midsize,12,Four or more years,1,"Under 1,000",1,Greene County,65804,Missouri,29,37.14,-93.25,Midwest,2.0,West North Central Division,4.0,www.bryanu.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,29077,3
3,164492,Anna Maria College,Paxton,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,63374,55501.0,55501.0,55501.0,6750.0,30000.0,13.50,135.0,24807.0,18057.0,26.8,72228.0,108342.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,42940.13,38660.11,63.62,57.27,171760.52,154640.44,257640.78,231960.66,20603.16,24883.08,Master's degree,20,Post-master's certificate,8,148,Rural: Fringe,41,Four or more years,1,"1,000 - 4,999",2,Worcester County,01612-1198,Massachusetts,25,42.33,-71.92,Northeast,1.0,New England Division,1.0,www.annamaria.edu/admission,A,Masters Colleges and Universities I,21,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,25027,2
4,164465,Amherst College,Amherst,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,87640,81787.0,81787.0,81787.0,6750.0,30000.0,13.50,135.0,1888.0,-4862.0,-7.2,-19448.0,-29172.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,20021.13,15741.11,29.66,23.32,80084.52,62964.44,120126.78,94446.66,20603.16,24883.08,Bachelor's degree,30,Bachelor's degree,5,-2,Suburb: Large,21,Four or more years,1,"1,000 - 4,999",2,Hampshire County,01002-5000,Massachusetts,25,42.37,-72.52,Northeast,1.0,New England Division,1.0,www.amherst.edu/admission/,A,Baccalaureate Colleges--Liberal Arts,31,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,25015,2

## Data Inspection

**Testing:**
- Verify column names include 'Unit ID', 'Affordability Gap', 'Net Price'
- Check for obvious data issues (null values, unexpected data types)
- Confirm data dictionary matches expectations

In [3]:
# Load College Results Data
college_file = '../College Results View 2021 Data Dump for Export.xlsx - College Results View 2021 Data .csv'

print("Loading College Results Data...")
df_college = pd.read_csv(college_file, low_memory=False)

print(f"✓ College Results data loaded successfully!")
print(f"  Shape: {df_college.shape}")
print(f"  Columns: {df_college.shape[1]}")
print(f"\nFirst 5 rows:")
df_college.head()

Loading College Results Data...
✓ College Results data loaded successfully!
  Shape: (6289, 192)
  Columns: 192

First 5 rows:

,UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION,Number of Bachelor Degrees Grand Total,Number of Bachelor Degrees Total Men,Number of Bachelor Degrees Total Women,Number of Bachelor Degrees White Total,Number of Bachelor Degrees White Men,Number of Bachelor Degrees White Women,Number of Bachelor Degrees American Indian or Alaska Native Men,Number of Bachelor Degrees American Indian or Alaska Native Total,Number of Bachelor Degrees American Indian or Alaska Native Women,Number of Bachelor Degrees Asian Men,Number of Bachelor Degrees Asian Total,Number of Bachelor Degrees Asian Women,Number of Bachelor Degrees Black or African American Men,Number of Bachelor Degrees Black or African American Total,Number of Bachelor Degrees Black or African American Women,Number of Bachelor Degrees Latino Men,Number of Bachelor Degrees Latino Total,Number of Bachelor Degrees Latina Women,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,"Number of Degrees Awarded in Science, Technology, Engineering, and Math",Number of Degrees Awarded in Arts and Humanities,Number of Degrees Awarded in Education,Number of Degrees Awarded in Social Sciences,Number of Degrees Awarded in Health Sciences,Number of Degrees Awarded in Business,Percent of Bachelor Degrees American Indian or Alaska Native Men,Percent of Bachelor Degrees American Indian or Alaska Native Total,Percent of Bachelor Degrees American Indian or Alaska Native Women,Percent of Bachelor Degrees Asian Men,Percent of Bachelor Degrees Asian Total,Percent of Bachelor Degrees Asian Women,Percent of Bachelor Degrees Black or African American Men,Percent of Bachelor Degrees Black or African American Total,Percent of Bachelor Degrees Black or African American Women,Percent of Bachelor Degrees Latino Men,Percent of Bachelor Degrees Latino Total,Percent of Bachelor Degrees Latina Women,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,Percent of Bachelor Degrees Men,Percent of Bachelor Degrees Women,Percent of Bachelor Degrees White Total,Percent of Bachelor Degrees White Men,Percent of Bachelor Degrees White Women,"Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",Percent of Bachelor Degrees Awarded in Arts and Humanities,Percent of Bachelor Degrees Awarded in Education,Percent of Bachelor Degrees Awarded in Social Sciences,Percent of Bachelor Degrees Awarded in Health Sciences,Percent of Bachelor Degrees Awarded in Business,Percent of American Indian or Alaska Native Undergraduates,Percent of Two or More Races Undergraduates,Percent of Asian Undergraduates,Percent of Black or African American Undergraduates,Percent of Latino Undergraduates,Percent of Native Hawaiian or Other Pacific Islander Undergraduates,Percent of White Undergraduates,Percent of Women Undergraduates,Percent of Men Undergraduates,Percent of Nonresident Undergraduates,Percent of Undergraduates Race-Ethnicity Unknown,Percent of Undergraduates Age 25 to 64,"Percent of Full-time, First-time Degree-Seeking Undergraduates",Percent of Undergraduates Enrolled Exclusively in Distance Education Courses,"Percent of First-Time, Full-Time International Undergraduates",Total Enrollment,"Number of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores","Percentage of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores",ACT English - 25th Percentile Score,ACT English - 75th Percentile Score,ACT Math - 25th Percentile Score,ACT Math - 75th Percentile Score,Number of First-Time Degree Certificate Seeking Students Submitting SAT Scores,Percent of First-Time Degree Certificate Seeking Students Submitting SAT Scores,SAT Evidence Based Reading and Writing - 25th Percentile Score,SAT Evidence Based Reading and Writing - 75th Percentile Score,SAT Math - 25th Percentile Score,SAT Math - 75th Percentile Score,Total Percent of Applicants Admitted,Total Percent of Men Admitted,Total Percent of Women Admitted,Bachelor's Degrees Awarded,Number of Students Receiving a Bachelor's Degree,Endowment Assets GASB per Student,Instructional Expenses GASB per Student,Endowment Assets FASB per Student,Instructional Expenses FASB per FTE,Instructional Expenses Per FTE,Bachelor's Degree Graduation Rate Within 4 Years - Total,Bachelor's Degree Graduation Rate Within 5 Years - Total,Bachelor's Degree Graduation Rate Within 6 Years - American Indian or Alaska Native,"Bachelor's Degree Graduation Rate Within 6 Years - Asian, Native Hawaiian, Pacific Islander",Bachelor's Degree Graduation Rate Within 6 Years - Asian,"Bachelor's Degree Graduation Rate Within 6 Years - Black, Non-Latino",Bachelor's Degree Graduation Rate Within 6 Years - Latino,Bachelor's Degree Graduation Rate Within 6 Years - Men,Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Women,Bachelor's Degree Graduation Rate Within 6 Years - White Non-Latino,Transfer Out Rate,Cost of Attendance for In-State Students Living on Campus,Average Cost of Attendance Out-of-State,Average Cost of Attendance In-District,Average Cost of Attendance In-State,"Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years","Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",Number of American Indian or Alaska Native Men,Number of American Indian or Alaska Native Total,Number of American Indian or Alaska Native Women,Number of Asian Men,Number of Asian Total,Number of Asian Women,Number of Black or African American Men,Number of Black or African American Total,Number of Black or African American Women,Number of Latino Men,Number of Latino Total,Number of Latina Women,Number of Native Hawaiian or Other Pacific Islander Men,Number of Native Hawaiian or Other Pacific Islander Total,Number of Native Hawaiian or Other Pacific Islander Women,Number of Men Enrolled,Number of Undergraduates Enrolled,Grand Total of Women Undergraduates Enrolled,Number of White Men Undergraduates Enrolled,Total Number of White Undergraduates Enrolled,Number of White Women Undergraduates Enrolled,Degree Level,Student Status,"First-Time, Full-Time Retention Rate",Student-to-Faculty Ratio,"Reported First-Time, Full-Time Undergraduate Enrollment",Carnegie Classification,City of Institution,Institutional Category,Institution Name,Institution Size Category,Degree of Urbanization,Sector of Institution,State of Institution,LATITUDE,LONGITUDE,Institution Web Address,Institution Type,Open Admissions Policy,"Out-of-State Average Tuition for First-Time, Full-Time Undergraduates","Average In-State Tuition for First-Time, Full-Time Undergraduates","Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded","Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Number of First-Time, Full-Time Undergraduates Awarded Pell Grants","Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants","Average Net Price After Grants, 2018-19","Average Net Price After Grants, 2019-20","Average Net Price After Grants, 2020-21","Average Net Price for Low-Income Students, 2018-19","Average Net Price for Low-Income Students, 2019-20","Average Net Price for Low-Income Students, 2020-21","Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21","Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",Asian American or Native American Pacific Islander-Serving Institution (AANAPISI),"Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)",Cohort Default Rate,Median Debt for Dependent Students,Median Debt of Completers,Historically Black College or University (HBCU),Hispanic-serving Institution (HSI),Median Debt for Independent Students,Instructional Expenditures Per Student,Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Students Working and Not Enrolled 10 Years After Entry,Native American Non-Tribal Institution (NANTI),Predominantly Black Institution (PBI),Percent of Full-Time Faculty,Percent of Part-Time Undergraduates,Tribal College or University (TCU),Public Institution GASB Endowment Assets,Private not-for-profit or Public Institution FASB Endowment Assets,Number of Undergraduates Age 25 and Older,Percent of Undergraduates Age 25 and Older
0,101301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,74.0,1.0,0.0,21.0,59.0,41.0,NaN,NaN,21.0,13.0,38.0,0.0,1627.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4735.0,NaN,NaN,4735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,15450.00000,11760.00000,11760.00000,2.0,34.0,0.0,0.0,0.0,3.0,3.0,0.0,160.0,366.0,206.0,6.0,9.0,3.0,0.0,0.0,0.0,237.0,480.0,243.0,55.0,85.0,30.0,1.0,22.0,62.0,14.0,1108.0,40,Selma,4,George C Wallace State Community College-Selma,2,32,4,AL,32,-87,https://www.wccs.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,7615.0,3501.0,8498.0,176.0,98.0,1495607.0,144.0,80.0,3759.0,5192.0,2247.0,3890.0,3733.0,1733.0,NaN,106.0,NaN,1733.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,4725.0,29770.0,25099.0,36041.0,0.0,1.0,0.5596,0.5087,0.0,NaN,NaN,344.0,0.070477
1,101435,244.0,103.0,141.0,176.0,70.0,106.0,0.0,2.0,2.0,2.0,2.0,0.0,19.0,38.0,19.0,6.0,12.0,6.0,0.0,0.0,0.0,34.0,0.0,8.0,5.0,3.0,86.0,0.000000,0.008197,0.008197,0.008197,0.008197,0.000000,0.077869,0.155738,0.077869,0.024590,0.049180,0.024590,0.000000,0.000000,0.000000,0.422131,0.577869,0.721311,0.286885,0.434426,0.139344,0.000000,0.032787,0.020492,0.012295,0.352459,0.0,4.0,1.0,20.0,6.0,0.0,66.0,45.0,55.0,0.0,20.0,4.0,30.0,0.0,0.0,844.0,157.0,62.0,20.0,25.0,17.0,24.0,17.0,7.0,510.0,560.0,470.0,510.0,69.0,69.0,70.0,244.0,244.0,NaN,NaN,70008.0,7326.0,7326.0,33.0,41.0,100.0,0.0,0.0,45.0,31.0,39.0,NaN,44.0,52.0,47.0,NaN,40728.0,36908.00000,36908.00000,36908.00000,0.0,40.0,1.0,4.0,3.0,2.0,6.0,4.0,99.0,153.0,54.0,33.0,52.0,19.0,0.0,0.0,0.0,451.0,792.0,341.0,289.0,532.0,243.0,1.0,22.0,72.0,15.0,858.0,31,Montgomery,2,Huntingdon College,1,12,2,AL,32,-86,www.huntingdon.edu/,Private Not-For-Profit Four-Year,2.0,25995.0,25995.0,8854.0,5070.0,12904.0,15688.0,219.0,100.0,3435618.0,87.0,40.0,21738.0,22026.0,23664.0,19380.0,17960.0,19670.0,23664.0,NaN,44.0,19670.0,0.0,0.0,0.100,15208.0,27000.0,0.0,NaN,23002.0,6497.0,44281.0,48806.0,47921.5,0.0,0.0,0.7595,0.1407,0.0,NaN,51910937.0,37.0,0.014700
2,101994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,1.0,61.0,1.0,0.0,34.0,61.0,39.0,NaN,NaN,37.0,20.0,5.0,0.0,374.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10843.0,NaN,NaN,10843.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13705.00000,10015.00000,10015.00000,0.0,41.0,0.0,0.0,0.0,1.0,1.0,0.0,25.0,77.0,52.0,0.0,1.0,1.0,0.0,0.0,0.0,74.0,144.0,70.0,45.0,61.0,16.0,1.0,22.0,73.0,12.0,258.0,40,Evergreen,4,Reid State Technical College,1,41,4,AL,31,-87,www.rstc.edu/,Public Two-Year,1.0,7380.0,3690.0,NaN,6428.0,4797.0,8043.0,35.0,95.0,281493.0,19.0,51.0,2918.0,1893.0,931.0,3022.0,1350.0,159.0,NaN,12.0,NaN,159.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,7854.0,22780.0,27625.0,27937.0,0.0,0.0,0.5313,0.5377,0.0,NaN,NaN,139.0,0.123996
3,102553,1044.0,427.0,617.0,581.0,240.0,341.0,7.0,31.0,24.0,32.0,83.0,51.0,6.0,24.0,18.0,37.0,97.0,60.0,5.0,16.0,11.0,73.0,0.0,0.0,47.0,255.0,194.0,0.006705,0.029693,0.022989,0.030651,0.079502,0.048851,0.005747,0.022989,0.017241,0.035441,0.092912,0.057471,0.004789,0.015326,0.010536,0.409004,0.590996,0.556513,0.229885,0.326628,0.069923,0.000000,0.000000,0.045019,0.244253,0.185824,5.0,10.0,7.0,3.0,8.0,3.0,49.0,61.0,39.0,2.0,6.0,43.0,6.0,49.0,1.0,10845.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.0,68.0,70.0,1044.0,1039.0,12069.0,13122.0,NaN,NaN,13122.0,15.0,27.0,5.0,31.0,33.0,13.0,31.0,31.0,15.0,32.0,33.0,38.0,16.0,30880.0,43325.33333,26719.33333,26719.33333,2.0,22.0,61.0,174.0,113.0,136.0,371.0,235.0,59.0,125.0,66.0,183.0,377.0,194.0,59.0,136.0,77.0,1803.0,4052.0,2249.0,931.0,1972.0,1041.0,1.0,22.0,69.0,12.0,6995.0,21,Anchorage,2,University of Alaska Anchorage,4,11,1,AK,61,-150,www.uaa.alaska.edu/,Public Four-Year,2.0,23072.0,7224.0,5628.0,5494.0,3943.0,7523.0,583.0,80.0,4385853.0,210.0,29.0,11961.0,11283.0,12816.0,9383.0,8971.0,9450.0,NaN,104.0,NaN,9450.0,0.0,0.0,0.034,9000.0,20500.0,0.0,NaN,14207.0,12307.0,47371.0,48868.0,47921.5,0.0,0.0,0.5181,0.4772,0.0,60842848.0,NaN,4536.0,0.147388
4,102632,144.0,46.0,98.0,92.0,29.0,63.0,2.0,10.0,8.0,2.0,6.0,4.0,0.0,0.0,0.0,3.0,10.0,7.0,0.0,1.0,1.0,16.0,2.0,25.0,21.0,0.0,42.0,0.013889,0.069444,0.055556,0.013889,0.041667,0.027778,0.000000,0.000000,0.000000,0.020833,0.069444,0.048611,0.000000,0.006944,0.006944,0.319444,0.680556,0.638889,0.201389,0.437500,0.111111,0.013889,0.173611,0.145833,0.000000,0.291667,14.0,11.0,3.0,1.0,7.0,2.0,55.0,65.0,35.0,5.0,5.0,50.0,6.0,52.0,1.0,1997.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,59.0,55.0,144.0,144.0,7459.0,15362.0,NaN,NaN,15362.0,13.0,27.0,0.0,50.0,33.0,NaN,0.0,35.0,100.0,29.0,26.0,29.0,24.0,20608.0,32680.00000,18544.00000,18544.00000,0.0,28.0,15.0,50.0,35.0,6.0,17.0,11.0,3.0,8.0,5.0,17.0,38.0,21.0,6.0,11.0,5.0,186.0,477.0,291.0,110.0,263.0,153.0,1.0,22.0,65.0,9.0,1005.0,21,Juneau,2,University of Alaska Southeast,2,33,1,AK,58,-135,www.uas.alaska.edu/,Public Four-Year,2.0,22742.0,7121.0,6059.0,3762.0,2929.0,8360.0,87.0,83.0,727299.0,35.0,33.0,11000.0,10506.0,7428.0,9605.0,6590.0,6157.0,NaN,20.0,NaN,6157.0,0.0,1.0,0.051,7500.0,20000.0,0.0,NaN,12467.0,15823.0,40460.0,41243.0,27937.0,1.0,0.0,0.5583,0.5447,0.0,6773153.0,NaN,911.0,0.172832

In [4]:
# Inspect column names and data types for both datasets
print("=" * 80)
print("AFFORDABILITY GAP DATA - Column Info")
print("=" * 80)
print(f"\nKey columns present:")
key_cols_aff = ['Unit ID', 'Affordability Gap', 'Net Price', 'Institution Name', 
                'State Abbreviation', 'Sector Name', 'MSI Status']
for col in key_cols_aff:
    if col in df_affordability.columns:
        print(f"  ✓ {col}")
    else:
        print(f"  ✗ {col} - NOT FOUND")

print(f"\nTotal columns: {len(df_affordability.columns)}")
print(f"\nColumn list (first 20):")
print(df_affordability.columns[:20].tolist())

print("\n" + "=" * 80)
print("COLLEGE RESULTS DATA - Column Info")
print("=" * 80)
print(f"\nKey columns present:")
key_cols_college = ['UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION', 
                    'Median Earnings of Students Working and Not Enrolled 10 Years After Entry',
                    'Bachelor\'s Degree Graduation Rate Bachelor Degree Within 6 Years - Total',
                    'Institution Name', 'Total Percent of Applicants Admitted']
for col in key_cols_college:
    if col in df_college.columns:
        print(f"  ✓ {col}")
    else:
        # Try to find similar column
        matches = [c for c in df_college.columns if col.lower()[:20] in c.lower()]
        if matches:
            print(f"  ≈ Similar: {matches[0][:60]}...")
        else:
            print(f"  ✗ {col} - NOT FOUND")

print(f"\nTotal columns: {len(df_college.columns)}")
print(f"\nColumn list (first 20):")
print(df_college.columns[:20].tolist())

================================================================================
AFFORDABILITY GAP DATA - Column Info
================================================================================

Key columns present:
  ✓ Unit ID
  ✗ Affordability Gap - NOT FOUND
  ✓ Net Price
  ✓ Institution Name
  ✓ State Abbreviation
  ✓ Sector Name
  ✓ MSI Status

Total columns: 79

Column list (first 20):
['Unit ID', 'Institution Name', 'City', 'State Abbreviation', 'Sector Name', 'Sector', 'MSI Status', 'MSI Type', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI', 'Average Work Study Award', 'Cost of Attendance: In State, On Campus', 'Cost of Attendance: Out of State', 'Cost of Attendance: In District', 'Cost of Attendance: In State']

================================================================================
COLLEGE RESULTS DATA - Column Info
================================================================================

Key columns present:
  ✓ UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION
  ✓ Median Earnings of Students Working and Not Enrolled 10 Years After Entry
  ✓ Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total
  ✓ Institution Name
  ✓ Total Percent of Applicants Admitted

Total columns: 192

Column list (first 20):
['UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION', 'Number of Bachelor Degrees Grand Total', 'Number of Bachelor Degrees Total Men', 'Number of Bachelor Degrees Total Women', 'Number of Bachelor Degrees White Total', 'Number of Bachelor Degrees White Men', 'Number of Bachelor Degrees White Women', 'Number of Bachelor Degrees American Indian or Alaska Native Men', 'Number of Bachelor Degrees American Indian or Alaska Native Total', 'Number of Bachelor Degrees American Indian or Alaska Native Women', 'Number of Bachelor Degrees Asian Men', 'Number of Bachelor Degrees Asian Total', 'Number of Bachelor Degrees Asian Women', 'Number of Bachelor Degrees Black or African American Men', 'Number of Bachelor Degrees Black or African American Total', 'Number of Bachelor Degrees Black or African American Women', 'Number of Bachelor Degrees Latino Men', 'Number of Bachelor Degrees Latino Total', 'Number of Bachelor Degrees Latina Women', 'Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men']

# Data Filtering

**Testing:**
- After filtering, expect 1,000-3,000 4-year institutions in each dataset
- Verify filtering logic correctly identifies bachelor's-granting institutions
- Document how many institutions are excluded and why

In [5]:
# Standardize institution ID column names
print("Standardizing institution ID column names...")

# Affordability data - rename to 'unit_id'
df_affordability = df_affordability.rename(columns={'Unit ID': 'unit_id'})

# College data - rename to 'unit_id'
df_college = df_college.rename(columns={
    'UNIQUE_IDENTIFICATION_NUMBER_OF_THE_INSTITUTION': 'unit_id'
})

print(f"✓ Affordability data: 'unit_id' column created")
print(f"✓ College data: 'unit_id' column created")
print(f"\nAffordability unit_id type: {df_affordability['unit_id'].dtype}")
print(f"College unit_id type: {df_college['unit_id'].dtype}")

Standardizing institution ID column names...
✓ Affordability data: 'unit_id' column created
✓ College data: 'unit_id' column created

Affordability unit_id type: int64
College unit_id type: int64

In [6]:
# Filter Affordability data to 4-year institutions
print("Filtering Affordability data to 4-year institutions...")
print(f"Before filtering: {len(df_affordability):,} institutions")

# Check available columns for filtering
if 'Highest Degree Offered Name' in df_affordability.columns:
    print("\nDegree levels in Affordability data:")
    print(df_affordability['Highest Degree Offered Name'].value_counts())
    
    # Filter for Bachelor's or higher
    df_affordability_4yr = df_affordability[
        df_affordability['Highest Degree Offered Name'].isin([
            "Bachelor's degree",
            "Master's degree", 
            "Doctor's degree - research/scholarship",
            "Doctor's degree -  professional practice",
            "Doctor's degree - research/scholarship and professional practice"
        ])
    ].copy()
elif 'Institution Level Name' in df_affordability.columns:
    print("\nInstitution levels in Affordability data:")
    print(df_affordability['Institution Level Name'].value_counts())
    
    df_affordability_4yr = df_affordability[
        df_affordability['Institution Level Name'] == 'Four or more years'
    ].copy()
else:
    print("Warning: Could not find filtering column. Using all data.")
    df_affordability_4yr = df_affordability.copy()

print(f"After filtering: {len(df_affordability_4yr):,} institutions")
print(f"Removed: {len(df_affordability) - len(df_affordability_4yr):,} institutions")

Filtering Affordability data to 4-year institutions...
Before filtering: 21,299 institutions

Degree levels in Affordability data:
Highest Degree Offered Name
Non-degree granting                                                 5329
Associate's degree                                                  5244
Master's degree                                                     3225
Bachelor's degree                                                   2731
Doctor's degree - research/scholarship and professional practice    2292
Doctor's degree - research/scholarship                              1233
Doctor's degree -  professional practice                            1070
Doctor's degree - other                                              145
{Not available}                                                       30
Name: count, dtype: int64
After filtering: 10,551 institutions
Removed: 10,748 institutions

In [7]:
# Filter College Results data to bachelor's-granting institutions
print("Filtering College Results data to bachelor's-granting institutions...")
print(f"Before filtering: {len(df_college):,} institutions")

# Check for degree level indicators
if 'Degree Level' in df_college.columns:
    print("\nDegree levels in College Results data:")
    print(df_college['Degree Level'].value_counts())
    
    df_college_4yr = df_college[
        df_college['Degree Level'] == 1  # 1 typically indicates bachelor's or higher
    ].copy()
elif 'Number of Bachelor Degrees Grand Total' in df_college.columns:
    # Filter for institutions that award bachelor's degrees
    df_college_4yr = df_college[
        df_college['Number of Bachelor Degrees Grand Total'].notna() & 
        (df_college['Number of Bachelor Degrees Grand Total'] > 0)
    ].copy()
else:
    print("Warning: Could not find filtering column. Using all data.")
    df_college_4yr = df_college.copy()

print(f"After filtering: {len(df_college_4yr):,} institutions")
print(f"Removed: {len(df_college) - len(df_college_4yr):,} institutions")

Filtering College Results data to bachelor's-granting institutions...
Before filtering: 6,289 institutions

Degree levels in College Results data:
Degree Level
1.0    5710
Name: count, dtype: int64
After filtering: 5,710 institutions
Removed: 579 institutions

# Data Merging

**Testing:**
- Merge should keep 500-2,000 institutions
- Document merge rate (matched / total)
- Check for duplicate unit_ids
- Verify merge produces expected column count

In [ ]:
# Merge datasets on unit_id (inner join)
print("Merging datasets on unit_id...")
print("=" * 80)

# Check for duplicates before merging
print(f"\nAffordability data:")
print(f"  Total institutions: {len(df_affordability_4yr):,}")
print(f"  Unique unit_ids: {df_affordability_4yr['unit_id'].nunique():,}")
print(f"  Duplicates: {len(df_affordability_4yr) - df_affordability_4yr['unit_id'].nunique()}")

print(f"\nCollege Results data:")
print(f"  Total institutions: {len(df_college_4yr):,}")
print(f"  Unique unit_ids: {df_college_4yr['unit_id'].nunique():,}")
print(f"  Duplicates: {len(df_college_4yr) - df_college_4yr['unit_id'].nunique()}")

# Perform inner join
df_merged = pd.merge(
    df_affordability_4yr,
    df_college_4yr,
    on='unit_id',
    how='inner',
    suffixes=('_affordability', '_college')
)

# Calculate merge statistics
n_affordability = len(df_affordability_4yr)
n_college = len(df_college_4yr)
n_merged = len(df_merged)

merge_rate_aff = (n_merged / n_affordability * 100) if n_affordability > 0 else 0
merge_rate_college = (n_merged / n_college * 100) if n_college > 0 else 0

print("\n" + "=" * 80)
print("MERGE RESULTS")
print("=" * 80)
print(f"  From Affordability: {n_affordability:,} institutions")
print(f"  From College Results: {n_college:,} institutions")
print(f"  Merged (matched): {n_merged:,} institutions")
print(f"\n  Merge rate from Affordability: {merge_rate_aff:.1f}%")
print(f"  Merge rate from College Results: {merge_rate_college:.1f}%")
print(f"\n  Total columns in merged dataset: {df_merged.shape[1]}")
print("=" * 80)

# Show sample of merged data
print(f"\nMerged data sample:")
df_merged.head()

Merging datasets on unit_id...
================================================================================

Affordability data:
  Total institutions: 10,551
  Unique unit_ids: 2,802
  Duplicates: 7749

College Results data:
  Total institutions: 5,710
  Unique unit_ids: 5,710
  Duplicates: 0

================================================================================
MERGE RESULTS
================================================================================
  From Affordability: 10,551 institutions
  From College Results: 5,710 institutions
  Merged (matched): 10,054 institutions

  Merge rate from Affordability: 95.3%
  Merge rate from College Results: 176.1%

  Total columns in merged dataset: 270
================================================================================

Merged data sample:

,unit_id,Institution Name_affordability,City,State Abbreviation,Sector Name,Sector,MSI Status,MSI Type,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,Average Work Study Award,"Cost of Attendance: In State, On Campus",Cost of Attendance: Out of State,Cost of Attendance: In District,Cost of Attendance: In State,Annual Income Estimate,Student Family Earnings Ceiling,State Minimum Wage,Income Earned from Working 10 Hours a Week at State's Minimum Wage,Net Price,Affordability Gap (net price minus income earned working 10 hrs at min wage),Weekly Hours to Close Gap,100% TTD Affordability Gap,150% TTD Affordability Gap,CPI Index,Monthly Center-Based Child Care Cost,Annual Center-Based Child Care Cost,Adjusted Monthly Center-Based Child Care Cost,Monthly Home-Based Child Care Cost,Adjusted Monthly Home-Based Child Care Cost,Annual Home-Based Child Care Cost,Student Parent Affordability Gap: Center-Based Care,Student Parent Affordability Gap: Home-Based Care,Weekly Hours to Close Gap: Center-Based Care,Weekly Hours to Close Gap: Home-Based Care,100% TTD Student Parent Affordability Gap: Center-Based Care,100% TTD Student Parent Affordability Gap: Home-Based Care,150% TTD Student Parent Affordability Gap: Center-Based Care,150% TTD Student Parent Affordability Gap: Home-Based Care,Adjusted Annual Home-Based Child Care Cost,Adjusted Annual Center-Based Child Care Cost,Highest Degree Offered Name,Highest Degree Offered,Highest Level Offered Name,Highest Level Offered,Combined Statistical Area,Degree of Localization Name,Degree of Localization,Institution Level Name,Institution Level,Institution Size Category Name,Institution Size Category_affordability,County Name,Zip Code,State,State Code (FIPS),Latitude,Longitude,Region,Region #,Sub Region,Sub Region #,Admissions Website,Institution Status,2000 Carnegie Classification Name,2000 Carnegie Classification,2015 Carnegie Classification Name,2015 Carnegie Classification,2018 Carnegie Classification Name,2018 Carnegie Classification,2021 Carnegie Classification Name,2021 Carnegie Classification,County Code,Control of Institution,Number of Bachelor Degrees Grand Total,Number of Bachelor Degrees Total Men,Number of Bachelor Degrees Total Women,Number of Bachelor Degrees White Total,Number of Bachelor Degrees White Men,Number of Bachelor Degrees White Women,Number of Bachelor Degrees American Indian or Alaska Native Men,Number of Bachelor Degrees American Indian or Alaska Native Total,Number of Bachelor Degrees American Indian or Alaska Native Women,Number of Bachelor Degrees Asian Men,Number of Bachelor Degrees Asian Total,Number of Bachelor Degrees Asian Women,Number of Bachelor Degrees Black or African American Men,Number of Bachelor Degrees Black or African American Total,Number of Bachelor Degrees Black or African American Women,Number of Bachelor Degrees Latino Men,Number of Bachelor Degrees Latino Total,Number of Bachelor Degrees Latina Women,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,"Number of Degrees Awarded in Science, Technology, Engineering, and Math",Number of Degrees Awarded in Arts and Humanities,Number of Degrees Awarded in Education,Number of Degrees Awarded in Social Sciences,Number of Degrees Awarded in Health Sciences,Number of Degrees Awarded in Business,Percent of Bachelor Degrees American Indian or Alaska Native Men,Percent of Bachelor Degrees American Indian or Alaska Native Total,Percent of Bachelor Degrees American Indian or Alaska Native Women,Percent of Bachelor Degrees Asian Men,Percent of Bachelor Degrees Asian Total,Percent of Bachelor Degrees Asian Women,Percent of Bachelor Degrees Black or African American Men,Percent of Bachelor Degrees Black or African American Total,Percent of Bachelor Degrees Black or African American Women,Percent of Bachelor Degrees Latino Men,Percent of Bachelor Degrees Latino Total,Percent of Bachelor Degrees Latina Women,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,Percent of Bachelor Degrees Men,Percent of Bachelor Degrees Women,Percent of Bachelor Degrees White Total,Percent of Bachelor Degrees White Men,Percent of Bachelor Degrees White Women,"Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",Percent of Bachelor Degrees Awarded in Arts and Humanities,Percent of Bachelor Degrees Awarded in Education,Percent of Bachelor Degrees Awarded in Social Sciences,Percent of Bachelor Degrees Awarded in Health Sciences,Percent of Bachelor Degrees Awarded in Business,Percent of American Indian or Alaska Native Undergraduates,Percent of Two or More Races Undergraduates,Percent of Asian Undergraduates,Percent of Black or African American Undergraduates,Percent of Latino Undergraduates,Percent of Native Hawaiian or Other Pacific Islander Undergraduates,Percent of White Undergraduates,Percent of Women Undergraduates,Percent of Men Undergraduates,Percent of Nonresident Undergraduates,Percent of Undergraduates Race-Ethnicity Unknown,Percent of Undergraduates Age 25 to 64,"Percent of Full-time, First-time Degree-Seeking Undergraduates",Percent of Undergraduates Enrolled Exclusively in Distance Education Courses,"Percent of First-Time, Full-Time International Undergraduates",Total Enrollment,"Number of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores","Percentage of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores",ACT English - 25th Percentile Score,ACT English - 75th Percentile Score,ACT Math - 25th Percentile Score,ACT Math - 75th Percentile Score,Number of First-Time Degree Certificate Seeking Students Submitting SAT Scores,Percent of First-Time Degree Certificate Seeking Students Submitting SAT Scores,SAT Evidence Based Reading and Writing - 25th Percentile Score,SAT Evidence Based Reading and Writing - 75th Percentile Score,SAT Math - 25th Percentile Score,SAT Math - 75th Percentile Score,Total Percent of Applicants Admitted,Total Percent of Men Admitted,Total Percent of Women Admitted,Bachelor's Degrees Awarded,Number of Students Receiving a Bachelor's Degree,Endowment Assets GASB per Student,Instructional Expenses GASB per Student,Endowment Assets FASB per Student,Instructional Expenses FASB per FTE,Instructional Expenses Per FTE,Bachelor's Degree Graduation Rate Within 4 Years - Total,Bachelor's Degree Graduation Rate Within 5 Years - Total,Bachelor's Degree Graduation Rate Within 6 Years - American Indian or Alaska Native,"Bachelor's Degree Graduation Rate Within 6 Years - Asian, Native Hawaiian, Pacific Islander",Bachelor's Degree Graduation Rate Within 6 Years - Asian,"Bachelor's Degree Graduation Rate Within 6 Years - Black, Non-Latino",Bachelor's Degree Graduation Rate Within 6 Years - Latino,Bachelor's Degree Graduation Rate Within 6 Years - Men,Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Women,Bachelor's Degree Graduation Rate Within 6 Years - White Non-Latino,Transfer Out Rate,Cost of Attendance for In-State Students Living on Campus,Average Cost of Attendance Out-of-State,Average Cost of Attendance In-District,Average Cost of Attendance In-State,"Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years","Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",Number of American Indian or Alaska Native Men,Number of American Indian or Alaska Native Total,Number of American Indian or Alaska Native Women,Number of Asian Men,Number of Asian Total,Number of Asian Women,Number of Black or African American Men,Number of Black or African American Total,Number of Black or African American Women,Number of Latino Men,Number of Latino Total,Number of Latina Women,Number of Native Hawaiian or Other Pacific Islander Men,Number of Native Hawaiian or Other Pacific Islander Total,Number of Native Hawaiian or Other Pacific Islander Women,Number of Men Enrolled,Number of Undergraduates Enrolled,Grand Total of Women Undergraduates Enrolled,Number of White Men Undergraduates Enrolled,Total Number of White Undergraduates Enrolled,Number of White Women Undergraduates Enrolled,Degree Level,Student Status,"First-Time, Full-Time Retention Rate",Student-to-Faculty Ratio,"Reported First-Time, Full-Time Undergraduate Enrollment",Carnegie Classification,City of Institution,Institutional Category,Institution Name_college,Institution Size Category_college,Degree of Urbanization,Sector of Institution,State of Institution,LATITUDE,LONGITUDE,Institution Web Address,Institution Type,Open Admissions Policy,"Out-of-State Average Tuition for First-Time, Full-Time Undergraduates","Average In-State Tuition for First-Time, Full-Time Undergraduates","Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded","Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Number of First-Time, Full-Time Undergraduates Awarded Pell Grants","Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants","Average Net Price After Grants, 2018-19","Average Net Price After Grants, 2019-20","Average Net Price After Grants, 2020-21","Average Net Price for Low-Income Students, 2018-19","Average Net Price for Low-Income Students, 2019-20","Average Net Price for Low-Income Students, 2020-21","Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21","Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",Asian American or Native American Pacific Islander-Serving Institution (AANAPISI),"Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)",Cohort Default Rate,Median Debt for Dependent Students,Median Debt of Completers,Historically Black College or University (HBCU),Hispanic-serving Institution (HSI),Median Debt for Independent Students,Instructional Expenditures Per Student,Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Students Working and Not Enrolled 10 Years After Entry,Native American Non-Tribal Institution (NANTI),Predominantly Black Institution (PBI),Percent of Full-Time Faculty,Percent of Part-Time Undergraduates,Tribal College or University (TCU),Public Institution GASB Endowment Assets,Private not-for-profit or Public Institution FASB Endowment Assets,Number of Undergraduates Age 25 and Older,Percent of Undergraduates Age 25 and Older
0,369516,Bryan University,Springfield,MO,"Private for-profit, 4-year or above",3,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2165.0,.,15693.0,15693.0,15693.0,5150.0,30000.0,10.3,103.0,21316.0,16166.0,31.4,64664.0,96996.0,1.08,1110.0,13320.0,1196.80,1258.8,1357.24,15105.6,30527.62,32452.86,59.28,63.02,122110.48,129811.44,183165.72,194717.16,16286.88,14361.60,Master's degree,20,Master's degree,7,-2,City: Midsize,12,Four or more years,1,"Under 1,000",1,Greene County,65804,Missouri,29,37.14,-93.25,Midwest,2.0,West North Central Division,4.0,www.bryanu.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,29077,3,26.0,6.0,20.0,15.0,5.0,10.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0,4.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,9.0,0.000000,0.000000,0.000000,0.000000,0.038462,0.038462,0.000000,0.153846,0.153846,0.000000,0.076923,0.076923,0.000000,0.000000,0.000000,0.230769,0.769231,0.576923,0.192308,0.384615,0.000000,0.000000,0.000000,0.000000,0.653846,0.346154,0.0,6.0,0.0,20.0,9.0,2.0,63.0,75.0,25.0,0.0,0.0,83.0,4.0,96.0,NaN,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,26.0,NaN,NaN,NaN,NaN,NaN,100.0,100.0,NaN,NaN,NaN,100.0,100.0,100.0,NaN,100.0,100.0,100.0,NaN,NaN,23453.00000,23453.00000,23453.00000,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,35.0,23.0,3.0,15.0,12.0,2.0,3.0,1.0,44.0,174.0,130.0,25.0,109.0,84.0,1.0,22.0,NaN,11.0,328.0,-2,Springfield,3,Bryan University,1,12,3,MO,37,-93,www.bryanu.edu/,Private For-Profit Four-Year,1.0,14494.0,14494.0,8283.0,6035.0,1000.0,6235.0,20.0,87.0,124691.0,20.0,87.0,19672.0,20239.0,19330.0,19887.0,20567.0,18616.0,19330.0,NaN,12.0,18616.0,0.0,0.0,0.127,13999.0,22402.0,0.0,NaN,19001.0,1732.0,29571.0,21997.0,36041.0,0.0,0.0,0.0000,0.0000,0.0,NaN,NaN,144.0,0.275862
1,164492,Anna Maria College,Paxton,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,63374,55501.0,55501.0,55501.0,6750.0,30000.0,13.5,135.0,24807.0,18057.0,26.8,72228.0,108342.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,42940.13,38660.11,63.62,57.27,171760.52,154640.44,257640.78,231960.66,20603.16,24883.08,Master's degree,20,Post-master's certificate,8,148,Rural: Fringe,41,Four or more years,1,"1,000 - 4,999",2,Worcester County,01612-1198,Massachusetts,25,42.33,-71.92,Northeast,1.0,New England Division,1.0,www.annamaria.edu/admission,A,Masters Colleges and Universities I,21,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,25027,2,251.0,138.0,113.0,161.0,89.0,72.0,0.0,1.0,1.0,1.0,6.0,5.0,13.0,26.0,13.0,6.0,22.0,16.0,0.0,0.0,0.0,0.0,2.0,7.0,4.0,57.0,35.0,0.000000,0.003984,0.003984,0.003984,0.023904,0.019920,0.051793,0.103586,0.051793,0.023904,0.087649,0.063745,0.000000,0.000000,0.000000,0.549801,0.450199,0.641434,0.354582,0.286853,0.000000,0.007968,0.027888,0.015936,0.227092,0.139442,0.0,2.0,1.0,14.0,10.0,0.0,62.0,43.0,57.0,0.0,17.0,19.0,17.0,11.0,8.0,1521.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,70.0,76.0,251.0,251.0,NaN,NaN,5267.0,5790.0,5790.0,40.0,47.0,33.0,50.0,50.0,24.0,47.0,34.0,NaN,48.0,58.0,57.0,NaN,57532.0,50049.33333,50049.33333,50049.33333,0.0,34.0,0.0,2.0,2.0,3.0,10.0,7.0,96.0,148.0,52.0,37.0,102.0,65.0,1.0,2.0,1.0,499.0,921.0,422.0,292.0,544.0,252.0,1.0,22.0,67.0,13.0,1001.0,21,Paxton,2,Anna Maria College,2,41,2,MA,42,-72,www.annamaria.edu/,Private Not-For-Profit Four-Year,2.0,37658.0,37658.0,9177.0,5779.0,25095.0,28097.0,241.0,100.0,6771326.0,103.0,43.0,24796.0,25617.0,24614.0,21602.0,22232.0,22305.0,24614.0,NaN,72.0,22305.0,0.0,0.0,0.061,15000.0,25000.0,0.0,NaN,17230.0,5641.0,51934.0,NaN,47921.5,0.0,0.0,0.2246,0.1474,0.0,NaN,6.022423e+06,214.0,0.063747
2,164465,Amherst College,Amherst,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,87640,81787.0,81787.0,81787.0,6750.0,30000.0,13.5,135.0,1888.0,-4862.0,-7.2,-19448.0,-29172.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,20021.13,15741.11,29.66,23.32,80084.52,62964.44,120126.78,94446.66,20603.16,24883.08,Bachelor's degree,30,Bachelor's degree,5,-2,Suburb: Large,21,Four or more years,1,"1,000 - 4,999",2,Hampshire County,01002-5000,Massachusetts,25,42.37,-72.52,Northeast,1.0,New England Division,1.0,www.amherst.edu/admission/,A,Baccalaureate Colleges--Liberal Arts,31,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,25015,2,395.0,198.0,197.0,178.0,95.0,83.0,3.0,5.0,2.0,25.0,55.0,30.0,13.0,40.0,27.0,23.0,50.0,27.0,0.0,0.0,0.0,55.0,0.0,0.0,78.0,0.0,0.0,0.007595,0.012658,0.005063,0.063291,0.139241,0.075949,0.032911,0.101266,0.068354,0.058228,0.126582,0.068354,0.000000,0.000000,0.000000,0.501266,0.498734,0.450633,0.240506,0.210127,0.139241,0.000000,0.000000,0.197468,0.000000,0.000000,0.0,7.0,15.0,10.0,15.0,0.0,39.0,51.0,49.0,NaN,NaN,1.0,26.0,0.0,12.0,1971.0,161.0,31.0,33.0,35.0,30.0,35.0,183.0,36.0,680.0,760.0,690.0,790.0,9.0,8.0,9.0,395.0,395.0,NaN,NaN,2132855.0,35852.0,35852.0,87.0,91.0,100.0,99.0,99.0,94.0,86.0,92.0,NaN,92.0,93.0,92.0,4.0,80050.0,74683.33333,74683.33333,74683.33333,0.0,95.0,1.0,5.0,4.0,135.0,299.0,164.0,99.0,203.0,104.0,140.0,304.0,164.0,3.0,4.0,1.0,957.0,1971.0,1014.0,378.0,764.0,386.0,1.0,22.0,98.0,7.0,1770.0,31,Amherst,2,Amherst College,2,21,2,MA,42,-73,www.amherst.edu/,Private Not-For-Profit Four-Year,2.0,60700.0,60700.0,8944.0,5833.0,57022.0,58644.0,264.0,61.0,15482030.0,89.0,21.0,16339.0,18832.0,18809.0,6079.0,4468.0,4625.0,18809.0,NaN,46.0,4625.0,0.0,0.0,0.000,NaN,13800.0,0.0,NaN,NaN,32264.0,72678.0,NaN,47921.5,0.0,0.0,0.9391,0.0000,0.0,NaN,2.565148e+09,28.0,0.004735
3,164447,American International College,Springfield,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,62300,55033.0,55033.0,55033.0,6750.0,30000.0,13.5,135.0,17645.0,10895.0,16.1,43580.0,65370.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,35778.13,31498.11,53.00,46.66,143112.52,125992.44,214668.78,188988.66,20603.16,24883.08,Doctor's degree - research/scholarship and pro...,11,Doctor's degree,9,-2,City: Midsize,12,Four or more years,1,"1,000 - 4,999",2,Hampden County,1109,Massachusetts,25,42.11,-72.56,Northeast,1.0,New England Division,1.0,www.aic.edu/admissions/,A,Masters Colleges and Universities I,21,Doctoral Universities: Moderate Research Activity,17,Master's Colleges & Universities: Larger Programs,18,Doctoral/Professional Universities_x000D_,17,25013,2,257.0,95.0,162.0,108.0,38.0,70.0,0.0,0.0,0.0,2.0,7.0,5.0,27.0,55.0,28.0,14.0,54.0,40.0,1.0,3.0,2.0,2.0,5.0,0.0,20.0,106.0,39.0,0.000000,0.000000,0.000000,0.007782,0.027237,0.019455,0.105058,0.214008,0.108949,0.054475,0.210117,0.155642,0.003891,0.011673,0.007782,0.369650,0.630350,0.420233,0.147860,0.272374,0.007782,0.019455,0.000000,0.077821,0.412451,0.151751,1.0,6.0,2.0,23.0,22.0,1.0,35.0,58.0,42.0,2.0,5.0,11.0,28.0,1.0,NaN,2244.0,0.0,0.0,NaN,NaN,NaN,NaN,15.0,4.0,470.0,555.0,470.0,555.0,58.0,55.0,61.0,257.0,257.0,NaN,NaN,9876.0,4757.0,4757.0,34.0,42.0,0.0,100.0,100.0,34.0,39.0,36.0,100.0,42.0,49.0,46.0,NaN,57240.0,50526.66667,50526.66667,50526.66667,0.0,65.0,4.0,7.0,3.0,5.0,19.0,14.0,153.0,287.0,134.0,97.0,274.0,177.0,7.0,16.0,9.0,506.0,1199.0,693.0,171.0,428.0,257.0,1.0,22.0,63.0,17.0,1334.0,21,Springfield,2,American International College,2,12,2,MA,42,-73,www.aic.edu/,Private Not-For-Profit Four-Year,2.0,39370.0,39370.0,8293.0,5184.0,26293.0,29701.0,325.0,98.0,9652925.0,176.0,53.0,21218.0,20876.0,20958.0,22785.0,24505.0,21196.0,20958.0,NaN,123.0,21196.0,0.0,0.0,0.061,19500.0,27000.0,0.0,NaN,25000.0,6709.0,49770.0,55568.0,47921.5,0.0,0.0,0.0950,0.0546,0.0,NaN,2.186915e+07,143.0,0.037008

In [11]:
df_merged.shape

(10054, 270)

# Missing Data Analysis

**Testing:**
- Identify key variables with >20% missing
- Create missingness heatmap
- Document patterns (e.g., do small institutions have more missing data?)
- Prioritize critical variables for analysis

In [ ]:
# Calculate missing percentage for all columns
print("Calculating missing data statistics...")

missing_stats = pd.DataFrame({
    'column': df_merged.columns,
    'missing_count': df_merged.isnull().sum().values,
    'missing_percent': (df_merged.isnull().sum() / len(df_merged) * 100).values
}).sort_values('missing_percent', ascending=False)

print(f"\nTop 20 columns with most missing data:")
print(missing_stats.head(20))

# Visualize missingness
import missingno as msno

# Select subset of columns for visualization (too many to show all)
cols_to_viz = missing_stats.head(30)['column'].tolist()

fig, ax = plt.subplots(figsize=(12, 6))
msno.matrix(df_merged[cols_to_viz], ax=ax, sparkline=False)
plt.title("Missing Data Pattern (Top 30 Columns)")
plt.tight_layout()
plt.show()

# Summary statistics
print(f"\n{'='*80}")
print("MISSING DATA SUMMARY")
print(f"{'='*80}")
print(f"Total columns: {len(df_merged.columns)}")
print(f"Columns with NO missing: {(missing_stats['missing_percent'] == 0).sum()}")
print(f"Columns with <10% missing: {(missing_stats['missing_percent'] < 10).sum()}")
print(f"Columns with 10-50% missing: {((missing_stats['missing_percent'] >= 10) & (missing_stats['missing_percent'] < 50)).sum()}")
print(f"Columns with >50% missing: {(missing_stats['missing_percent'] >= 50).sum()}")
print(f"{'='*80}")

In [ ]:
# Identify critical variables and check their missingness
print("Checking missingness in CRITICAL variables...")
print("=" * 80)

critical_vars = {
    'Treatment': ['Affordability Gap (net price minus income earned working 10 hrs at min wage)', 'Net Price'],
    'Outcomes': [
        'Median Earnings of Students Working and Not Enrolled 10 Years After Entry',
        "Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total"
    ],
    'Selectivity': [
        'Total Percent of Applicants Admitted',
        'SAT Evidence Based Reading and Writing - 25th Percentile Score',
        'ACT English - 25th Percentile Score'
    ],
    'Demographics': [
        "Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants",
        'Percent of Bachelor Degrees White Total',
        'Percent of Bachelor Degrees Black or African American Total',
        'Percent of Bachelor Degrees Latino Total'
    ],
    'Resources': [
        'Instructional Expenses Per FTE',
        'Endowment Assets FASB per Student'
    ],
    'Institution': [
        'Sector of Institution',
        'State of Institution',
        'Institution Size Category'
    ],
    'MSI': ['HBCU', 'HSI', 'TCU']
}

for category, vars in critical_vars.items():
    print(f"\n{category}:")
    for var in vars:
        if var in df_merged.columns:
            missing_pct = (df_merged[var].isnull().sum() / len(df_merged) * 100)
            status = "✓" if missing_pct < 20 else "⚠" if missing_pct < 50 else "✗"
            print(f"  {status} {var[:60]:<60} Missing: {missing_pct:5.1f}%")
        else:
            print(f"  ✗ {var[:60]:<60} NOT FOUND")

print("=" * 80)

# Data Cleaning

**Testing:**
- After listwise deletion, final sample should be 500+ institutions
- Verify no missing values remain in critical columns
- Document which institutions are excluded and why
- Check if excluded institutions differ systematically from included ones

In [ ]:
# Apply listwise deletion for rows missing critical variables
print("Applying listwise deletion for critical variables...")
print("=" * 80)

# Define absolutely required variables (must be present for analysis)
required_vars = [
    'Affordability Gap (net price minus income earned working 10 hrs at min wage)',
    'Median Earnings of Students Working and Not Enrolled 10 Years After Entry',
    "Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total"
]

print(f"\nRequired variables for analysis:")
for var in required_vars:
    if var in df_merged.columns:
        print(f"  ✓ {var}")
    else:
        print(f"  ✗ {var} - NOT FOUND (will try to find alternative)")

# Filter out rows with missing required variables
df_clean = df_merged.copy()
initial_n = len(df_clean)

for var in required_vars:
    if var in df_clean.columns:
        before = len(df_clean)
        df_clean = df_clean[df_clean[var].notna()].copy()
        after = len(df_clean)
        removed = before - after
        print(f"\n  Removed {removed:,} institutions missing '{var[:50]}...'")
        print(f"    Remaining: {after:,}")

final_n = len(df_clean)
removed_total = initial_n - final_n

print(f"\n{'='*80}")
print(f"CLEANING RESULTS")
print(f"{'='*80}")
print(f"  Before cleaning: {initial_n:,} institutions")
print(f"  After cleaning: {final_n:,} institutions")
print(f"  Removed: {removed_total:,} institutions ({removed_total/initial_n*100:.1f}%)")
print(f"{'='*80}")

# Verify completeness
print(f"\nVerifying completeness of required variables...")
for var in required_vars:
    if var in df_clean.columns:
        missing = df_clean[var].isnull().sum()
        print(f"  {var[:50]:<50} Missing: {missing}")

# Check if we met our minimum sample size goal
if final_n >= 500:
    print(f"\n✓ SUCCESS: Final sample of {final_n:,} institutions exceeds minimum (500)")
else:
    print(f"\n⚠ WARNING: Final sample of {final_n:,} institutions is below minimum (500)")

In [ ]:
# Save cleaned merged dataset
import os

output_dir = '../outputs/data'
os.makedirs(output_dir, exist_ok=True)

output_file = os.path.join(output_dir, 'merged_clean.csv')
df_clean.to_csv(output_file, index=False)

print(f"✓ Cleaned merged dataset saved to: {output_file}")
print(f"  Final shape: {df_clean.shape}")
print(f"  Institutions: {len(df_clean):,}")
print(f"  Columns: {df_clean.shape[1]}")

In [13]:
merged = pd.read_csv("../outputs/data/merged_clean.csv")

In [14]:
merged

,unit_id,Institution Name_affordability,City,State Abbreviation,Sector Name,Sector,MSI Status,MSI Type,HBCU,PBI,ANNHI,TRIBAL,AANAPII,HSI,NANTI,Average Work Study Award,"Cost of Attendance: In State, On Campus",Cost of Attendance: Out of State,Cost of Attendance: In District,Cost of Attendance: In State,Annual Income Estimate,Student Family Earnings Ceiling,State Minimum Wage,Income Earned from Working 10 Hours a Week at State's Minimum Wage,Net Price,Affordability Gap (net price minus income earned working 10 hrs at min wage),Weekly Hours to Close Gap,100% TTD Affordability Gap,150% TTD Affordability Gap,CPI Index,Monthly Center-Based Child Care Cost,Annual Center-Based Child Care Cost,Adjusted Monthly Center-Based Child Care Cost,Monthly Home-Based Child Care Cost,Adjusted Monthly Home-Based Child Care Cost,Annual Home-Based Child Care Cost,Student Parent Affordability Gap: Center-Based Care,Student Parent Affordability Gap: Home-Based Care,Weekly Hours to Close Gap: Center-Based Care,Weekly Hours to Close Gap: Home-Based Care,100% TTD Student Parent Affordability Gap: Center-Based Care,100% TTD Student Parent Affordability Gap: Home-Based Care,150% TTD Student Parent Affordability Gap: Center-Based Care,150% TTD Student Parent Affordability Gap: Home-Based Care,Adjusted Annual Home-Based Child Care Cost,Adjusted Annual Center-Based Child Care Cost,Highest Degree Offered Name,Highest Degree Offered,Highest Level Offered Name,Highest Level Offered,Combined Statistical Area,Degree of Localization Name,Degree of Localization,Institution Level Name,Institution Level,Institution Size Category Name,Institution Size Category_affordability,County Name,Zip Code,State,State Code (FIPS),Latitude,Longitude,Region,Region #,Sub Region,Sub Region #,Admissions Website,Institution Status,2000 Carnegie Classification Name,2000 Carnegie Classification,2015 Carnegie Classification Name,2015 Carnegie Classification,2018 Carnegie Classification Name,2018 Carnegie Classification,2021 Carnegie Classification Name,2021 Carnegie Classification,County Code,Control of Institution,Number of Bachelor Degrees Grand Total,Number of Bachelor Degrees Total Men,Number of Bachelor Degrees Total Women,Number of Bachelor Degrees White Total,Number of Bachelor Degrees White Men,Number of Bachelor Degrees White Women,Number of Bachelor Degrees American Indian or Alaska Native Men,Number of Bachelor Degrees American Indian or Alaska Native Total,Number of Bachelor Degrees American Indian or Alaska Native Women,Number of Bachelor Degrees Asian Men,Number of Bachelor Degrees Asian Total,Number of Bachelor Degrees Asian Women,Number of Bachelor Degrees Black or African American Men,Number of Bachelor Degrees Black or African American Total,Number of Bachelor Degrees Black or African American Women,Number of Bachelor Degrees Latino Men,Number of Bachelor Degrees Latino Total,Number of Bachelor Degrees Latina Women,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Number of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,"Number of Degrees Awarded in Science, Technology, Engineering, and Math",Number of Degrees Awarded in Arts and Humanities,Number of Degrees Awarded in Education,Number of Degrees Awarded in Social Sciences,Number of Degrees Awarded in Health Sciences,Number of Degrees Awarded in Business,Percent of Bachelor Degrees American Indian or Alaska Native Men,Percent of Bachelor Degrees American Indian or Alaska Native Total,Percent of Bachelor Degrees American Indian or Alaska Native Women,Percent of Bachelor Degrees Asian Men,Percent of Bachelor Degrees Asian Total,Percent of Bachelor Degrees Asian Women,Percent of Bachelor Degrees Black or African American Men,Percent of Bachelor Degrees Black or African American Total,Percent of Bachelor Degrees Black or African American Women,Percent of Bachelor Degrees Latino Men,Percent of Bachelor Degrees Latino Total,Percent of Bachelor Degrees Latina Women,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Men,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Total,Percent of Bachelor Degrees Native Hawaiian or Other Pacific Islander Women,Percent of Bachelor Degrees Men,Percent of Bachelor Degrees Women,Percent of Bachelor Degrees White Total,Percent of Bachelor Degrees White Men,Percent of Bachelor Degrees White Women,"Percent of Bachelor Degrees Awarded in Science, Technology, Engineering, and Math",Percent of Bachelor Degrees Awarded in Arts and Humanities,Percent of Bachelor Degrees Awarded in Education,Percent of Bachelor Degrees Awarded in Social Sciences,Percent of Bachelor Degrees Awarded in Health Sciences,Percent of Bachelor Degrees Awarded in Business,Percent of American Indian or Alaska Native Undergraduates,Percent of Two or More Races Undergraduates,Percent of Asian Undergraduates,Percent of Black or African American Undergraduates,Percent of Latino Undergraduates,Percent of Native Hawaiian or Other Pacific Islander Undergraduates,Percent of White Undergraduates,Percent of Women Undergraduates,Percent of Men Undergraduates,Percent of Nonresident Undergraduates,Percent of Undergraduates Race-Ethnicity Unknown,Percent of Undergraduates Age 25 to 64,"Percent of Full-time, First-time Degree-Seeking Undergraduates",Percent of Undergraduates Enrolled Exclusively in Distance Education Courses,"Percent of First-Time, Full-Time International Undergraduates",Total Enrollment,"Number of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores","Percentage of First-Time, Full-Time Degree Certificate Seeking Students Submitting ACT Scores",ACT English - 25th Percentile Score,ACT English - 75th Percentile Score,ACT Math - 25th Percentile Score,ACT Math - 75th Percentile Score,Number of First-Time Degree Certificate Seeking Students Submitting SAT Scores,Percent of First-Time Degree Certificate Seeking Students Submitting SAT Scores,SAT Evidence Based Reading and Writing - 25th Percentile Score,SAT Evidence Based Reading and Writing - 75th Percentile Score,SAT Math - 25th Percentile Score,SAT Math - 75th Percentile Score,Total Percent of Applicants Admitted,Total Percent of Men Admitted,Total Percent of Women Admitted,Bachelor's Degrees Awarded,Number of Students Receiving a Bachelor's Degree,Endowment Assets GASB per Student,Instructional Expenses GASB per Student,Endowment Assets FASB per Student,Instructional Expenses FASB per FTE,Instructional Expenses Per FTE,Bachelor's Degree Graduation Rate Within 4 Years - Total,Bachelor's Degree Graduation Rate Within 5 Years - Total,Bachelor's Degree Graduation Rate Within 6 Years - American Indian or Alaska Native,"Bachelor's Degree Graduation Rate Within 6 Years - Asian, Native Hawaiian, Pacific Islander",Bachelor's Degree Graduation Rate Within 6 Years - Asian,"Bachelor's Degree Graduation Rate Within 6 Years - Black, Non-Latino",Bachelor's Degree Graduation Rate Within 6 Years - Latino,Bachelor's Degree Graduation Rate Within 6 Years - Men,Bachelor's Degree Graduation Rate Within 6 Years - Native Hawaiian or Other Pacific Islander,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Total,Bachelor's Degree Graduation Rate Bachelor Degree Within 6 Years - Women,Bachelor's Degree Graduation Rate Within 6 Years - White Non-Latino,Transfer Out Rate,Cost of Attendance for In-State Students Living on Campus,Average Cost of Attendance Out-of-State,Average Cost of Attendance In-District,Average Cost of Attendance In-State,"Percent Full-time, First-time, Pell Grant Recipients Still Enrolled at Same Institution - 8 Years","Percent Full-time, First-time, Pell Grant Recipients Receiving an Award - 6 Years",Number of American Indian or Alaska Native Men,Number of American Indian or Alaska Native Total,Number of American Indian or Alaska Native Women,Number of Asian Men,Number of Asian Total,Number of Asian Women,Number of Black or African American Men,Number of Black or African American Total,Number of Black or African American Women,Number of Latino Men,Number of Latino Total,Number of Latina Women,Number of Native Hawaiian or Other Pacific Islander Men,Number of Native Hawaiian or Other Pacific Islander Total,Number of Native Hawaiian or Other Pacific Islander Women,Number of Men Enrolled,Number of Undergraduates Enrolled,Grand Total of Women Undergraduates Enrolled,Number of White Men Undergraduates Enrolled,Total Number of White Undergraduates Enrolled,Number of White Women Undergraduates Enrolled,Degree Level,Student Status,"First-Time, Full-Time Retention Rate",Student-to-Faculty Ratio,"Reported First-Time, Full-Time Undergraduate Enrollment",Carnegie Classification,City of Institution,Institutional Category,Institution Name_college,Institution Size Category_college,Degree of Urbanization,Sector of Institution,State of Institution,LATITUDE,LONGITUDE,Institution Web Address,Institution Type,Open Admissions Policy,"Out-of-State Average Tuition for First-Time, Full-Time Undergraduates","Average In-State Tuition for First-Time, Full-Time Undergraduates","Average Amount of Loans Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Average Amount of Federal, State, Local, or Institutional Grant Aid Awarded","Number of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Percent of First-Time, Full-Time Undergraduates Awarded Federal, State, Local or Institutional Grant Aid","Total Amount of Federal, State, Local or Institutional Grant Aid Awarded to First-Time, Full-Time Undergraduates","Number of First-Time, Full-Time Undergraduates Awarded Pell Grants","Percent of First-Time, Full-Time Undergraduates Awarded Pell Grants","Average Net Price After Grants, 2018-19","Average Net Price After Grants, 2019-20","Average Net Price After Grants, 2020-21","Average Net Price for Low-Income Students, 2018-19","Average Net Price for Low-Income Students, 2019-20","Average Net Price for Low-Income Students, 2020-21","Average Net Price After Grants- Students Awarded a Grant or Scholarship, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students In-State, 2020-21","Number Awarded a Grant or Scholarship - Low-Income Students, 2020-21","Average Net Price After Grants - Low-Income Students Awarded Financial Aid, 2020-21",Asian American or Native American Pacific Islander-Serving Institution (AANAPISI),"Alaska-Native, Native Hawaiian-Serving Institution (ANNHSI)",Cohort Default Rate,Median Debt for Dependent Students,Median Debt of Completers,Historically Black College or University (HBCU),Hispanic-serving Institution (HSI),Median Debt for Independent Students,Instructional Expenditures Per Student,Median Earnings of Dependent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Independent Students Working and Not Enrolled 10 Years After Entry,Median Earnings of Students Working and Not Enrolled 10 Years After Entry,Native American Non-Tribal Institution (NANTI),Predominantly Black Institution (PBI),Percent of Full-Time Faculty,Percent of Part-Time Undergraduates,Tribal College or University (TCU),Public Institution GASB Endowment Assets,Private not-for-profit or Public Institution FASB Endowment Assets,Number of Undergraduates Age 25 and Older,Percent of Undergraduates Age 25 and Older
0,369516,Bryan University,Springfield,MO,"Private for-profit, 4-year or above",3,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2165.0,.,15693.0,15693.0,15693.0,5150.0,30000.0,10.30,103.0,21316.0,16166.0,31.4,64664.0,96996.0,1.08,1110.0,13320.0,1196.80,1258.8,1357.24,15105.6,30527.62,32452.86,59.28,63.02,122110.48,129811.44,183165.72,194717.16,16286.88,14361.60,Master's degree,20,Master's degree,7,-2,City: Midsize,12,Four or more years,1,"Under 1,000",1,Greene County,65804,Missouri,29,37.14,-93.25,Midwest,2.0,West North Central Division,4.0,www.bryanu.edu/,A,"Not applicable, not in Carnegie universe (not ...",-2,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,Baccalaureate/Associate's Colleges: Mixed Bacc...,23,29077,3,26.0,6.0,20.0,15.0,5.0,10.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,4.0,4.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,9.0,0.000000,0.000000,0.000000,0.000000,0.038462,0.038462,0.000000,0.153846,0.153846,0.000000,0.076923,0.076923,0.000000,0.000000,0.000000,0.230769,0.769231,0.576923,0.192308,0.384615,0.000000,0.000000,0.000000,0.000000,0.653846,0.346154,0.0,6.0,0.0,20.0,9.0,2.0,63.0,75.0,25.0,0.0,0.0,83.0,4.0,96.0,NaN,184.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,26.0,NaN,NaN,NaN,NaN,NaN,100.0,100.0,NaN,NaN,NaN,100.0,100.0,100.0,NaN,100.0,100.0,100.0,NaN,NaN,23453.00000,23453.00000,23453.00000,0.0,62.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,35.0,23.0,3.0,15.0,12.0,2.0,3.0,1.0,44.0,174.0,130.0,25.0,109.0,84.0,1.0,22.0,NaN,11.0,328.0,-2,Springfield,3,Bryan University,1,12,3,MO,37,-93,www.bryanu.edu/,Private For-Profit Four-Year,1.0,14494.0,14494.0,8283.0,6035.0,1000.0,6235.0,20.0,87.0,124691.0,20.0,87.0,19672.0,20239.0,19330.0,19887.0,20567.0,18616.0,19330.0,NaN,12.0,18616.0,0.0,0.0,0.127,13999.0,22402.0,0.0,NaN,19001.0,1732.0,29571.0,21997.0,36041.0,0.0,0.0,0.0000,0.0000,0.0,NaN,NaN,144.0,0.275862
1,164492,Anna Maria College,Paxton,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,63374,55501.0,55501.0,55501.0,6750.0,30000.0,13.50,135.0,24807.0,18057.0,26.8,72228.0,108342.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,42940.13,38660.11,63.62,57.27,171760.52,154640.44,257640.78,231960.66,20603.16,24883.08,Master's degree,20,Post-master's certificate,8,148,Rural: Fringe,41,Four or more years,1,"1,000 - 4,999",2,Worcester County,01612-1198,Massachusetts,25,42.33,-71.92,Northeast,1.0,New England Division,1.0,www.annamaria.edu/admission,A,Masters Colleges and Universities I,21,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,Master's Colleges & Universities: Medium Programs,19,25027,2,251.0,138.0,113.0,161.0,89.0,72.0,0.0,1.0,1.0,1.0,6.0,5.0,13.0,26.0,13.0,6.0,22.0,16.0,0.0,0.0,0.0,0.0,2.0,7.0,4.0,57.0,35.0,0.000000,0.003984,0.003984,0.003984,0.023904,0.019920,0.051793,0.103586,0.051793,0.023904,0.087649,0.063745,0.000000,0.000000,0.000000,0.549801,0.450199,0.641434,0.354582,0.286853,0.000000,0.007968,0.027888,0.015936,0.227092,0.139442,0.0,2.0,1.0,14.0,10.0,0.0,62.0,43.0,57.0,0.0,17.0,19.0,17.0,11.0,8.0,1521.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.0,70.0,76.0,251.0,251.0,NaN,NaN,5267.0,5790.0,5790.0,40.0,47.0,33.0,50.0,50.0,24.0,47.0,34.0,NaN,48.0,58.0,57.0,NaN,57532.0,50049.33333,50049.33333,50049.33333,0.0,34.0,0.0,2.0,2.0,3.0,10.0,7.0,96.0,148.0,52.0,37.0,102.0,65.0,1.0,2.0,1.0,499.0,921.0,422.0,292.0,544.0,252.0,1.0,22.0,67.0,13.0,1001.0,21,Paxton,2,Anna Maria College,2,41,2,MA,42,-72,www.annamaria.edu/,Private Not-For-Profit Four-Year,2.0,37658.0,37658.0,9177.0,5779.0,25095.0,28097.0,241.0,100.0,6771326.0,103.0,43.0,24796.0,25617.0,24614.0,21602.0,22232.0,22305.0,24614.0,NaN,72.0,22305.0,0.0,0.0,0.061,15000.0,25000.0,0.0,NaN,17230.0,5641.0,51934.0,NaN,47921.5,0.0,0.0,0.2246,0.1474,0.0,NaN,6.022423e+06,214.0,0.063747
2,164465,Amherst College,Amherst,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,87640,81787.0,81787.0,81787.0,6750.0,30000.0,13.50,135.0,1888.0,-4862.0,-7.2,-19448.0,-29172.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,20021.13,15741.11,29.66,23.32,80084.52,62964.44,120126.78,94446.66,20603.16,24883.08,Bachelor's degree,30,Bachelor's degree,5,-2,Suburb: Large,21,Four or more years,1,"1,000 - 4,999",2,Hampshire County,01002-5000,Massachusetts,25,42.37,-72.52,Northeast,1.0,New England Division,1.0,www.amherst.edu/admission/,A,Baccalaureate Colleges--Liberal Arts,31,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,Baccalaureate Colleges: Arts & Sciences Focus,21,25015,2,395.0,198.0,197.0,178.0,95.0,83.0,3.0,5.0,2.0,25.0,55.0,30.0,13.0,40.0,27.0,23.0,50.0,27.0,0.0,0.0,0.0,55.0,0.0,0.0,78.0,0.0,0.0,0.007595,0.012658,0.005063,0.063291,0.139241,0.075949,0.032911,0.101266,0.068354,0.058228,0.126582,0.068354,0.000000,0.000000,0.000000,0.501266,0.498734,0.450633,0.240506,0.210127,0.139241,0.000000,0.000000,0.197468,0.000000,0.000000,0.0,7.0,15.0,10.0,15.0,0.0,39.0,51.0,49.0,NaN,NaN,1.0,26.0,0.0,12.0,1971.0,161.0,31.0,33.0,35.0,30.0,35.0,183.0,36.0,680.0,760.0,690.0,790.0,9.0,8.0,9.0,395.0,395.0,NaN,NaN,2132855.0,35852.0,35852.0,87.0,91.0,100.0,99.0,99.0,94.0,86.0,92.0,NaN,92.0,93.0,92.0,4.0,80050.0,74683.33333,74683.33333,74683.33333,0.0,95.0,1.0,5.0,4.0,135.0,299.0,164.0,99.0,203.0,104.0,140.0,304.0,164.0,3.0,4.0,1.0,957.0,1971.0,1014.0,378.0,764.0,386.0,1.0,22.0,98.0,7.0,1770.0,31,Amherst,2,Amherst College,2,21,2,MA,42,-73,www.amherst.edu/,Private Not-For-Profit Four-Year,2.0,60700.0,60700.0,8944.0,5833.0,57022.0,58644.0,264.0,61.0,15482030.0,89.0,21.0,16339.0,18832.0,18809.0,6079.0,4468.0,4625.0,18809.0,NaN,46.0,4625.0,0.0,0.0,0.000,NaN,13800.0,0.0,NaN,NaN,32264.0,72678.0,NaN,47921.5,0.0,0.0,0.9391,0.0000,0.0,NaN,2.565148e+09,28.0,0.004735
3,164447,American International College,Springfield,MA,"Private not-for-profit, 4-year or above",2,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2015.0,62300,55033.0,55033.0,55033.0,6750.0,30000.0,13.50,135.0,17645.0,10895.0,16.1,43580.0,65370.0,1.08,1923.2,23078.4,2073.59,1592.4,1716.93,19108.8,35778.13,31498.11,53.00,46.66,143112.52,125992.44,214668.78,188988.66,20603.16,24883.08,Doctor's degree - research/scholarship and pro...,11,Doctor's degree,9,-2,City: Midsize,12,Four or more years,1,"1,000 - 4,999",2,Hampden County,1109,Massachusetts,25,42.11,-72.56,Northeast,1.0,New England Division,1.0,www.aic.edu/admissions/,A,Masters Colleges and Universities I,21,Doctoral Universities: Moderate Research Activity,17,Master's Colleges & Universities: Larger Programs,18,Doctoral/Professional Universities_x000D_,17,25013,2,257.0,95.0,162.0,108.0,38.0,70.0,0.0,0.0,0.0,2.0,7.0,5.0,27.0,55.0,28.0,14.0,54.0,40.0,1.0,3.0,2.0,2.0,5.0,0.0,20.0,106.0,39.0,0.000000,0.000000,0.000000,0.007782,0.027237,0.019455,0.105058,0.214008,0.108949,0.054475,0.210117,0.155642,0.003891,0.011673,0.007782,0.369650,0.630350,0.420233,0.147860,0.272374,0.007782,0.019455,0.000000,0.077821,0.412451,0.151751,1.0,6.0,2.0,23.0,22.0,1.0,35.0,58.0,42.0,2.0,5.0,11.0,28.0,1.0,NaN,2244.0,0.0,0.0,NaN,NaN,NaN,NaN,15.0,4.0,470.0,555.0,470.0,555.0,58.0,55.0,61.0,257.0,257.0,NaN,NaN,9876.0,4757.0,4757.0,34.0,42.0,0.0,100.0,100.0,34.0,39.0,36.0,100.0,42.0,49.0,46.0,NaN,57240.0,50526.66667,50526.66667,50526.66667,0.0,65.0,4.0,7.0,3.0,5.0,19.0,14.0,153.0,287.0,134.0,97.0,274.0,177.0,7.0,16.0,9.0,506.0,1199.0,693.0,171.0,428.0,257.0,1.0,22.0,63.0,17.0,1334.0,21,Springfield,2,American International College,2,12,2,MA,42,-73,www.aic.edu/,Private Not-For-Profit Four-Year,2.0,39370.0,39370.0,8293.0,5184.0,26293.0,29701.0,325.0,98.0,9652925.0,176.0,53.0,21218.0,20876.0,20958.0,22785.0,24505.0,21196.0,20958.0,NaN,123.0,21196.0,0.0,0.0,0.061,19500.0,27000.0,0.0,NaN,25000.0,6709.0,49770.0,55568.0,47921.5,0.0,0.0,0.0950,0.0546,0.0,NaN,2.186915e+07,143.0,0.037008